#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("LGSA.Droid.Resource", IsApplication=true)]

namespace LGSA.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040000
			public const int drawer_sections = 2130968576;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int background_color = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int drawer_icon = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int drawer_shadow = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050003
			public const int dark_gray = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int drawer_background = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int drawer_item_text_color = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int light_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f06000b
			public const int ActivitySpacing = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int ActivitySpacingNegative = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int ElementSpacing = 2131099658;
			
			// aapt resource value: 0x7f060005
			public const int ExpandableListViewHeaderPadding = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int HeaderPadding = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int LargePadding = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int LargeText = 2131099648;
			
			// aapt resource value: 0x7f06000d
			public const int ListItemIndent = 2131099661;
			
			// aapt resource value: 0x7f060007
			public const int MediumPadding = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int MediumText = 2131099649;
			
			// aapt resource value: 0x7f060009
			public const int MicroPadding = 2131099657;
			
			// aapt resource value: 0x7f060003
			public const int MicroText = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int SmallPadding = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int SmallText = 2131099650;
			
			// aapt resource value: 0x7f06000f
			public const int drawer_item_padding = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int drawer_width = 2131099662;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int drawer_shadow_dark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int drawer_shadow_light = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_navigation_drawer_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_navigation_drawer_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int splash = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090001
			public const int content_frame = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int drawer_layout = 2131296256;
			
			// aapt resource value: 0x7f090002
			public const int left_drawer = 2131296258;
			
			// aapt resource value: 0x7f090005
			public const int schedule_date = 2131296261;
			
			// aapt resource value: 0x7f090003
			public const int schedule_dateContainer = 2131296259;
			
			// aapt resource value: 0x7f090007
			public const int schedule_description = 2131296263;
			
			// aapt resource value: 0x7f090004
			public const int schedule_month = 2131296260;
			
			// aapt resource value: 0x7f090006
			public const int schedule_weekday = 2131296262;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int item_menu = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int news = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int schedule = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int schedule_item = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int ApplicationName = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int ContactFragmentName = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int Hello = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int NewsFragmentName = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int ScheduleFragmentName = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int drawer_close = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int drawer_open = 2131165189;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080002
			public const int BaseTheme = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int BaseThemeLight = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int BaseThemeLightDarkActionBar = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int Theme = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int Theme_Splash = 2131230726;
			
			// aapt resource value: 0x7f080004
			public const int ThemeLight = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int ThemeLightDarkActionBar = 2131230725;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
