#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("LGSA.Droid.Resource", IsApplication=true)]

namespace LGSA.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040000
			public const int drawer_sections = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int filter_division = 2130968577;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int background_color = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int drawer_icon = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int drawer_shadow = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050031
			public const int aliceblue = 2131034161;
			
			// aapt resource value: 0x7f050027
			public const int antiquewhite = 2131034151;
			
			// aapt resource value: 0x7f050081
			public const int aqua = 2131034241;
			
			// aapt resource value: 0x7f050066
			public const int aquamarine = 2131034214;
			
			// aapt resource value: 0x7f05002f
			public const int azure = 2131034159;
			
			// aapt resource value: 0x7f05002c
			public const int beige = 2131034156;
			
			// aapt resource value: 0x7f050012
			public const int bisque = 2131034130;
			
			// aapt resource value: 0x7f050090
			public const int black = 2131034256;
			
			// aapt resource value: 0x7f050010
			public const int blanchedalmond = 2131034128;
			
			// aapt resource value: 0x7f05008c
			public const int blue = 2131034252;
			
			// aapt resource value: 0x7f05005f
			public const int blueviolet = 2131034207;
			
			// aapt resource value: 0x7f050053
			public const int brown = 2131034195;
			
			// aapt resource value: 0x7f050039
			public const int burlywood = 2131034169;
			
			// aapt resource value: 0x7f050071
			public const int cadetblue = 2131034225;
			
			// aapt resource value: 0x7f050067
			public const int chartreuse = 2131034215;
			
			// aapt resource value: 0x7f050043
			public const int chocolate = 2131034179;
			
			// aapt resource value: 0x7f05001c
			public const int coral = 2131034140;
			
			// aapt resource value: 0x7f050070
			public const int cornflowerblue = 2131034224;
			
			// aapt resource value: 0x7f05000c
			public const int cornsilk = 2131034124;
			
			// aapt resource value: 0x7f05003c
			public const int crimson = 2131034172;
			
			// aapt resource value: 0x7f050082
			public const int cyan = 2131034242;
			
			// aapt resource value: 0x7f050003
			public const int dark_gray = 2131034115;
			
			// aapt resource value: 0x7f05008e
			public const int darkblue = 2131034254;
			
			// aapt resource value: 0x7f050088
			public const int darkcyan = 2131034248;
			
			// aapt resource value: 0x7f05004b
			public const int darkgoldenrod = 2131034187;
			
			// aapt resource value: 0x7f050052
			public const int darkgray = 2131034194;
			
			// aapt resource value: 0x7f05008b
			public const int darkgreen = 2131034251;
			
			// aapt resource value: 0x7f050048
			public const int darkkhaki = 2131034184;
			
			// aapt resource value: 0x7f05005d
			public const int darkmagenta = 2131034205;
			
			// aapt resource value: 0x7f050072
			public const int darkolivegreen = 2131034226;
			
			// aapt resource value: 0x7f05001b
			public const int darkorange = 2131034139;
			
			// aapt resource value: 0x7f050056
			public const int darkorchid = 2131034198;
			
			// aapt resource value: 0x7f05005e
			public const int darkred = 2131034206;
			
			// aapt resource value: 0x7f050036
			public const int darksalmon = 2131034166;
			
			// aapt resource value: 0x7f05005b
			public const int darkseagreen = 2131034203;
			
			// aapt resource value: 0x7f050075
			public const int darkslateblue = 2131034229;
			
			// aapt resource value: 0x7f05007b
			public const int darkslategray = 2131034235;
			
			// aapt resource value: 0x7f050086
			public const int darkturquoise = 2131034246;
			
			// aapt resource value: 0x7f050058
			public const int darkviolet = 2131034200;
			
			// aapt resource value: 0x7f050020
			public const int deeppink = 2131034144;
			
			// aapt resource value: 0x7f050087
			public const int deepskyblue = 2131034247;
			
			// aapt resource value: 0x7f05006e
			public const int dimgray = 2131034222;
			
			// aapt resource value: 0x7f05007f
			public const int dodgerblue = 2131034239;
			
			// aapt resource value: 0x7f050001
			public const int drawer_background = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int drawer_item_text_color = 2131034114;
			
			// aapt resource value: 0x7f05004c
			public const int firebrick = 2131034188;
			
			// aapt resource value: 0x7f05000a
			public const int floralwhite = 2131034122;
			
			// aapt resource value: 0x7f05007d
			public const int forestgreen = 2131034237;
			
			// aapt resource value: 0x7f050021
			public const int fuchsia = 2131034145;
			
			// aapt resource value: 0x7f05003b
			public const int gainsboro = 2131034171;
			
			// aapt resource value: 0x7f050029
			public const int ghostwhite = 2131034153;
			
			// aapt resource value: 0x7f050016
			public const int gold = 2131034134;
			
			// aapt resource value: 0x7f05003e
			public const int goldenrod = 2131034174;
			
			// aapt resource value: 0x7f050062
			public const int gray = 2131034210;
			
			// aapt resource value: 0x7f05008a
			public const int green = 2131034250;
			
			// aapt resource value: 0x7f050050
			public const int greenyellow = 2131034192;
			
			// aapt resource value: 0x7f050030
			public const int honeydew = 2131034160;
			
			// aapt resource value: 0x7f05001d
			public const int hotpink = 2131034141;
			
			// aapt resource value: 0x7f050045
			public const int indianred = 2131034181;
			
			// aapt resource value: 0x7f050073
			public const int indigo = 2131034227;
			
			// aapt resource value: 0x7f050006
			public const int ivory = 2131034118;
			
			// aapt resource value: 0x7f050032
			public const int khaki = 2131034162;
			
			// aapt resource value: 0x7f050037
			public const int lavender = 2131034167;
			
			// aapt resource value: 0x7f05000e
			public const int lavenderblush = 2131034126;
			
			// aapt resource value: 0x7f050068
			public const int lawngreen = 2131034216;
			
			// aapt resource value: 0x7f05000b
			public const int lemonchiffon = 2131034123;
			
			// aapt resource value: 0x7f050004
			public const int lgsa_purple = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int light_background = 2131034112;
			
			// aapt resource value: 0x7f050051
			public const int lightblue = 2131034193;
			
			// aapt resource value: 0x7f050033
			public const int lightcoral = 2131034163;
			
			// aapt resource value: 0x7f050038
			public const int lightcyan = 2131034168;
			
			// aapt resource value: 0x7f050025
			public const int lightgoldenrodyellow = 2131034149;
			
			// aapt resource value: 0x7f05005a
			public const int lightgreen = 2131034202;
			
			// aapt resource value: 0x7f050041
			public const int lightgrey = 2131034177;
			
			// aapt resource value: 0x7f050018
			public const int lightpink = 2131034136;
			
			// aapt resource value: 0x7f05001a
			public const int lightsalmon = 2131034138;
			
			// aapt resource value: 0x7f05007e
			public const int lightseagreen = 2131034238;
			
			// aapt resource value: 0x7f050060
			public const int lightskyblue = 2131034208;
			
			// aapt resource value: 0x7f05006a
			public const int lightslategray = 2131034218;
			
			// aapt resource value: 0x7f05004e
			public const int lightsteelblue = 2131034190;
			
			// aapt resource value: 0x7f050007
			public const int lightyellow = 2131034119;
			
			// aapt resource value: 0x7f050084
			public const int lime = 2131034244;
			
			// aapt resource value: 0x7f05007a
			public const int limegreen = 2131034234;
			
			// aapt resource value: 0x7f050026
			public const int linen = 2131034150;
			
			// aapt resource value: 0x7f050022
			public const int magenta = 2131034146;
			
			// aapt resource value: 0x7f050065
			public const int maroon = 2131034213;
			
			// aapt resource value: 0x7f05006f
			public const int mediumaquamarine = 2131034223;
			
			// aapt resource value: 0x7f05008d
			public const int mediumblue = 2131034253;
			
			// aapt resource value: 0x7f05004a
			public const int mediumorchid = 2131034186;
			
			// aapt resource value: 0x7f050059
			public const int mediumpurple = 2131034201;
			
			// aapt resource value: 0x7f050079
			public const int mediumseagreen = 2131034233;
			
			// aapt resource value: 0x7f050069
			public const int mediumslateblue = 2131034217;
			
			// aapt resource value: 0x7f050085
			public const int mediumspringgreen = 2131034245;
			
			// aapt resource value: 0x7f050074
			public const int mediumturquoise = 2131034228;
			
			// aapt resource value: 0x7f050046
			public const int mediumvioletred = 2131034182;
			
			// aapt resource value: 0x7f050080
			public const int midnightblue = 2131034240;
			
			// aapt resource value: 0x7f05002a
			public const int mintcream = 2131034154;
			
			// aapt resource value: 0x7f050011
			public const int mistyrose = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int moccasin = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int navajowhite = 2131034132;
			
			// aapt resource value: 0x7f05008f
			public const int navy = 2131034255;
			
			// aapt resource value: 0x7f050024
			public const int oldlace = 2131034148;
			
			// aapt resource value: 0x7f050063
			public const int olive = 2131034211;
			
			// aapt resource value: 0x7f05006c
			public const int olivedrab = 2131034220;
			
			// aapt resource value: 0x7f050019
			public const int orange = 2131034137;
			
			// aapt resource value: 0x7f05001f
			public const int orangered = 2131034143;
			
			// aapt resource value: 0x7f05003f
			public const int orchid = 2131034175;
			
			// aapt resource value: 0x7f050034
			public const int palegoldenrod = 2131034164;
			
			// aapt resource value: 0x7f050057
			public const int palegreen = 2131034199;
			
			// aapt resource value: 0x7f05004f
			public const int paleturquoise = 2131034191;
			
			// aapt resource value: 0x7f05003d
			public const int palevioletred = 2131034173;
			
			// aapt resource value: 0x7f05000f
			public const int papayawhip = 2131034127;
			
			// aapt resource value: 0x7f050015
			public const int peachpuff = 2131034133;
			
			// aapt resource value: 0x7f050044
			public const int peru = 2131034180;
			
			// aapt resource value: 0x7f050017
			public const int pink = 2131034135;
			
			// aapt resource value: 0x7f05003a
			public const int plum = 2131034170;
			
			// aapt resource value: 0x7f05004d
			public const int powderblue = 2131034189;
			
			// aapt resource value: 0x7f050064
			public const int purple = 2131034212;
			
			// aapt resource value: 0x7f050023
			public const int red = 2131034147;
			
			// aapt resource value: 0x7f050049
			public const int rosybrown = 2131034185;
			
			// aapt resource value: 0x7f050077
			public const int royalblue = 2131034231;
			
			// aapt resource value: 0x7f05005c
			public const int saddlebrown = 2131034204;
			
			// aapt resource value: 0x7f050028
			public const int salmon = 2131034152;
			
			// aapt resource value: 0x7f05002e
			public const int sandybrown = 2131034158;
			
			// aapt resource value: 0x7f05007c
			public const int seagreen = 2131034236;
			
			// aapt resource value: 0x7f05000d
			public const int seashell = 2131034125;
			
			// aapt resource value: 0x7f050054
			public const int sienna = 2131034196;
			
			// aapt resource value: 0x7f050047
			public const int silver = 2131034183;
			
			// aapt resource value: 0x7f050061
			public const int skyblue = 2131034209;
			
			// aapt resource value: 0x7f05006d
			public const int slateblue = 2131034221;
			
			// aapt resource value: 0x7f05006b
			public const int slategray = 2131034219;
			
			// aapt resource value: 0x7f050009
			public const int snow = 2131034121;
			
			// aapt resource value: 0x7f050083
			public const int springgreen = 2131034243;
			
			// aapt resource value: 0x7f050076
			public const int steelblue = 2131034230;
			
			// aapt resource value: 0x7f050042
			public const int tan = 2131034178;
			
			// aapt resource value: 0x7f050089
			public const int teal = 2131034249;
			
			// aapt resource value: 0x7f050040
			public const int thistle = 2131034176;
			
			// aapt resource value: 0x7f05001e
			public const int tomato = 2131034142;
			
			// aapt resource value: 0x7f050078
			public const int turquoise = 2131034232;
			
			// aapt resource value: 0x7f050035
			public const int violet = 2131034165;
			
			// aapt resource value: 0x7f05002d
			public const int wheat = 2131034157;
			
			// aapt resource value: 0x7f050005
			public const int white = 2131034117;
			
			// aapt resource value: 0x7f05002b
			public const int whitesmoke = 2131034155;
			
			// aapt resource value: 0x7f050008
			public const int yellow = 2131034120;
			
			// aapt resource value: 0x7f050055
			public const int yellowgreen = 2131034197;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f06000b
			public const int ActivitySpacing = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int ActivitySpacingNegative = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int ElementSpacing = 2131099658;
			
			// aapt resource value: 0x7f060005
			public const int ExpandableListViewHeaderPadding = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int HeaderPadding = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int LargePadding = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int LargeText = 2131099648;
			
			// aapt resource value: 0x7f06000d
			public const int ListItemIndent = 2131099661;
			
			// aapt resource value: 0x7f060007
			public const int MediumPadding = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int MediumText = 2131099649;
			
			// aapt resource value: 0x7f060009
			public const int MicroPadding = 2131099657;
			
			// aapt resource value: 0x7f060003
			public const int MicroText = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int SmallPadding = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int SmallText = 2131099650;
			
			// aapt resource value: 0x7f06000f
			public const int drawer_item_padding = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int drawer_width = 2131099662;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int drawer_shadow_dark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int drawer_shadow_light = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_navigation_drawer_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_navigation_drawer_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int logo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int splash = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0008
			public const int action_schedule_search = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int action_schedule_share = 2131361801;
			
			// aapt resource value: 0x7f0a0001
			public const int content_frame = 2131361793;
			
			// aapt resource value: 0x7f0a0000
			public const int drawer_layout = 2131361792;
			
			// aapt resource value: 0x7f0a0002
			public const int left_drawer = 2131361794;
			
			// aapt resource value: 0x7f0a0005
			public const int schedule_date = 2131361797;
			
			// aapt resource value: 0x7f0a0003
			public const int schedule_dateContainer = 2131361795;
			
			// aapt resource value: 0x7f0a0007
			public const int schedule_description = 2131361799;
			
			// aapt resource value: 0x7f0a0004
			public const int schedule_month = 2131361796;
			
			// aapt resource value: 0x7f0a0006
			public const int schedule_weekday = 2131361798;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int item_menu = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int news = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int schedule = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int schedule_item = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int schedule_menu = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f07000d
			public const int All = 2131165197;
			
			// aapt resource value: 0x7f070001
			public const int ApplicationName = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int ContactFragmentName = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int Hello = 2131165184;
			
			// aapt resource value: 0x7f07000b
			public const int Junior = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int Lassie = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int LittleLassie = 2131165193;
			
			// aapt resource value: 0x7f070003
			public const int NewsFragmentName = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int ScheduleFragmentName = 2131165186;
			
			// aapt resource value: 0x7f07000c
			public const int Senior = 2131165196;
			
			// aapt resource value: 0x7f070008
			public const int action_schedule_filter = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int action_schedule_search = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int drawer_close = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int drawer_open = 2131165189;
			
			// aapt resource value: 0x7f07000e
			public const int schedule_share = 2131165198;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080002
			public const int BaseTheme = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int BaseThemeLight = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int BaseThemeLightDarkActionBar = 2131230721;
			
			// aapt resource value: 0x7f08000c
			public const int LGSA_ActionBar_Text = 2131230732;
			
			// aapt resource value: 0x7f080007
			public const int LGSA_Purple = 2131230727;
			
			// aapt resource value: 0x7f080009
			public const int PurpleActionBar = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int PurpleActionMenu = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int PurpleDropDownList = 2131230731;
			
			// aapt resource value: 0x7f080003
			public const int Theme = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int Theme_Splash = 2131230726;
			
			// aapt resource value: 0x7f08000d
			public const int Theme_stylingactionbar_widget = 2131230733;
			
			// aapt resource value: 0x7f080004
			public const int ThemeLight = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int ThemeLightDarkActionBar = 2131230725;
			
			// aapt resource value: 0x7f080008
			public const int _lgsa_purple = 2131230728;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
